### ISSUE TITLE
What sort of performance characteristics does this have compared to the C lib w/bindings?

### ISSUE THREAD

**Issue by douglasg14b** [RichardVasquez/h3net#12]
As the title says, what sort of performance characteristics does this have vs the original c lib?

**Comment by RichardVasquez** [comment]
In terms of accuracy, it passes all the Uber H3 provided unit tests.

That accuracy has a cost of speed, as I'm using decimal value types, and performing Taylor series approximations for trig functions instead of doubles and the built in Math.* library.  I haven't done any formal tests, so I can't give you an objective measurement.
