### ISSUE TITLE
Inaccurate API results

### ISSUE THREAD

**Issue by Kadajski** [RichardVasquez/h3net#13]
Hey thanks for the library. I am trying to use this but I am getting inconsistent behavior and after doing some debugging some APIs just seem to return incorrect results

If I run this for example the boundaries returned are nowhere near the original coordinates
```
var index = Api.GeoToH3(new GeoCoord(40.759114m, -73.988546m), 6);
Api.H3ToGeoBoundary(index, out var boundary);
foreach (var vert in boundary.Verts)
{
    Console.WriteLine(vert);
}
```

The results I get are
```
GeoCoord: (Lat,Lng) 0.082073252, -1.731777291
GeoCoord: (Lat,Lng) 0.081735427, -1.732271961
GeoCoord: (Lat,Lng) 0.081157382, -1.732255957
GeoCoord: (Lat,Lng) 0.080917029, -1.731745166
GeoCoord: (Lat,Lng) 0.081254917, -1.731250309
GeoCoord: (Lat,Lng) 0.081833095, -1.731266429
GeoCoord: (Lat,Lng) 0.000000000, 0.000000000
GeoCoord: (Lat,Lng) 0.000000000, 0.000000000
GeoCoord: (Lat,Lng) 0.000000000, 0.000000000
GeoCoord: (Lat,Lng) 0.000000000, 0.000000000
```

If I do the same in the h3 js library with the following code
```
let testIndex = h3.geoToH3(40.759114, -73.988546, 6);
let testBoundaries = h3.h3ToGeoBoundary(testIndex);
for (let test of testBoundaries)
{
    console.log(test);
}
```

I get the results
```
(2) [40.77396440203853, -73.94384490497664]
(2) [40.76659438221225, -73.98852232840895]
(2) [40.73537602621502, -74.0022744646159]
(2) [40.71154393543933, -73.97139376102862]
(2) [40.71890320501306, -73.92676660481357]
(2) [40.75010530534532, -73.91296992347031]
```

I noticed this behavior as I was trying to investigate why I couldn't get kring to work correctly in this library. I dont get results similar to what I'd expect if I write similar code to what works in the uber js lib.

Thanks

**Comment by RichardVasquez** [comment]
Hi!  Thanks for the feedback.  I see two issues here, and let me see if I can address them.

I'm surprised at the count of boundary.Verts (you shouldn't have gotten all those 0.00 values), and I'll check on that this weekend.

As for the values of the vertices, h3net, like the C origin of h3 uses radians instead of degrees, so your constructor referenced a point that was 40+ radians in latitude, and -73 radians in longitude.  I'm guessing the h3 js library uses degrees.

I'm trying to stick as close to the C version as possible in terms of syntax and data, while adding my own extensions to things as needed, so I may have you covered there.

Try replacing `new GeoCoord(40.759114m, -73.988546m)` above with `new GeoCoord().SetDegrees(40.759114m, -73.988546m)` and let me know how that works for you, please.

**Comment by Kadajski** [comment]
Hey thanks for the reply.  I did not realise everything was in radians. That was indeed the issue I had

```
var index = Api.GeoToH3(new GeoCoord().SetDegrees(40.759114m, -73.988546m), 6);
Api.H3ToGeoBoundary(index, out var boundary);
foreach (var vert in boundary.Verts)
{
    Console.WriteLine("Long - {0}, Lat - {1}", Api.RadiansToDegrees(vert.Longitude), Api.RadiansToDegrees(vert.Latitude));                
}
```

Then the output is correct besides the few extra empty verts
```
Long - -73.943844904976639977555484375, Lat - 40.773964402038516120428794794
Long - -73.988522328408956466279997340, Lat - 40.766594382212235457638129668
Long - -74.002274464615897648304313968, Lat - 40.735376026215016062333884191
Long - -73.971393761028624171119601120, Lat - 40.711543935439325426606493556
Long - -73.926766604813558494871809700, Lat - 40.718903205013056769288427628
Long - -73.912969923470322232525440013, Lat - 40.750105305345319676384740582
Long - 0, Lat - 0
Long - 0, Lat - 0
Long - 0, Lat - 0
Long - 0, Lat - 0
```

thanks for the help
