### ISSUE TITLE
.NET target framework support

### ISSUE THREAD

**Issue by mattias01** [RichardVasquez/h3net#16]
The purpose of #14 was so that I can use this library in a .NET 4.6.2 project that I have.
The choice of targeting the older .NET standard 2.0 and not using C# 8 features was delibarate, so that projects not using the latest .NET versions can use this library.

Supported frameworks are detailed here:
https://docs.microsoft.com/en-us/dotnet/standard/net-standard

For example:
- .NET standard 2.0 supports .NET 4.6.1+ (2015) and .NET Core 2.0+
- .NET standard 2.1 only supports .NET Core 3.0+ (2019)

Since #14, the library itself does not need to target .NET standard 2.1 and C# 8, but some of the code in the test suite does. The test suite code can of course also be ported to not use C# 8 features, but I'm not sure I see the value of doing that.

I'm suggesting retargeting the library back to .NET standard 2.0 (instead of .NET standard 2.1), removing the C# 8 requirement and letting the test suite only target .NET 5.

I can supply a PR if necessary.

**Comment by RichardVasquez** [comment]
I'm going to have to think on this.  I grok what happened, and the change did come about since the unit test actions failed on GitHub after your change.

I did some reading last night on multi targeting, and this might be doable to some degree, and if so, I'll try to get a change up here.

Two things to consider though, on your part.

1) I've got my own projects I'm working on, which is why this code exists.  I'm writing my code in C# 8. 

2) Something like the switch syntax is relatively minor, and keeping that compatible isn't a real big deal at this point.  However, for some of the optimizations I'm looking at, I'm pondering things like C# records, and I may look at other things available as the technology improves.

I don't have an answer for you just yet, but I may experiment with multi targeting for a bit and see how much of a PITA it is or isn't.  But I see that as only a temporary measure.

**Comment by mattias01** [comment]
When I started looking at libraries in c# for using H3, I found three libraries, none which worked in my project.
- H3.net/pocketken.H3 which only targets .NET 5 and adds in more functionality than only handling H3 that I do not want.
  - https://github.com/pocketken/H3.net
- H3Standard/H3 which wraps the c-library. The nuget package only bundles the compiled c library for windows and does not seem to be actively developed.
  - https://github.com/entrepreneur-interet-general/H3.Standard
- H3net/H3Lib (this library) which was targeting .Net Core 3.1, but turned out to be able to target .Net standard 2.0 with minimal changes.

So the landscape for using H3 in C# is not that great, but if your library supports .Net standard 2.0, that would be an improvement. Your library would attract users that simply cannot use any of the other libraries, if that is something that is of interest to you. A lot of people (especially enterprises) are still stuck on older .net versions and will be for some time. I will soon have the projects I work on migrated to a newer version, so for me personally this is an issue that will go away. If ththe latest version would be published as a Nuget package, I would be able to re-target it since it actually compiles with the .Net implementation I’m using.

I agree with you that adapting a few switch cases isn’t a big deal, but when you have to use conditional compilation to support multiple targets, it is not fun.

What you do with your library is of course all up to you. I have no demands here, only suggestions. I'm grateful that you have written and released it as open source.

**Comment by RichardVasquez** [comment]
Fair enough.

I'm going to try some testing with multi-targeting and possibly update this.  I tend to just keep moving forward, but I grok legacy code needing to be able to use stuff as well.

I'll push assuming tests pass.
