### ISSUE TITLE
Implementation is not the same as Uber's C library

### ISSUE THREAD

**Issue by DmyMi** [RichardVasquez/h3net#22]
Hello, I've tried to integrate two services - one to populate the DB with h3 hashes (using Java h3 bindings) and the other for searching (using your .Net Core implementation), and found out that your implementation does not match Uber's.
For the same coordinates (i.e., `52.353553,4.883015`) and resolution (i.e., `5`) I get:
- `599166370717892607 => 0x0850aaa3bfffffff` from your library
- `599425793185021951 => 0x085196953fffffff` from Java bindings

I've double checked with Python bindings, and as they have the same C lib underneath I got the same result as Java.

Is it intended to be that way or is it a bug? Because it works fine when using only your library, but integration with different implementations is not possible

**Comment by pocketken** [comment]
> Hello, I've tried to integrate two services - one to populate the DB with h3 hashes (using Java h3 bindings) and the other for searching (using your .Net Core implementation), and found out that your implementation does not match Uber's. For the same coordinates (i.e., `52.353553,4.883015`) and resolution (i.e., `5`) I get:
> 
> * `599166370717892607 => 0x0850aaa3bfffffff` from your library
> * `599425793185021951 => 0x085196953fffffff` from Java bindings

I happened across this and wanted to validate whether or not my port was exhibiting the same issue, and I noticed that I can replicate your results if I feed degrees in instead of radians:

```
H3Index.FromGeoCoord(new GeoCoord(52.353553 * M_PI_180, 4.883015 * M_PI_180), 5);
//= 85196953fffffff
H3Index.FromGeoCoord(new GeoCoord(52.353553, 4.883015), 5);
//= 850aaa3bfffffff
```

If you're using the regular constructor `GeoCoord` should be given radians and not degrees.  It looks like there's a `GeoCoord.SetDegrees` extension method you can use to specify degrees, or alternatively you can just multiply by pi / 180 as I have above to convert them to radians.

**Comment by DmyMi** [comment]
@pocketken Thank you, that works. Didn't cross my mind that it's a conversion issue, but as you mentioned it I double checked and it does say radians in the field comments :)
